### ISSUE TITLE
Button component for minigames

### ISSUE THREAD

**Issue by Meerschwein** [Scodun/Bop-It#6]
Effort: M

**Comment by Scodun** [comment]
Class that extends Fragment and implements a listener interface for button click. (Predefined correct answer)
The job of this class is to render the buttons and to handle listeners dynamically. So the minigame gets only the value "correct button pressed" or "wrong button pressed"

Should init with: Custom Button Array or predefined templates like "true or false"

Examples: 
True False with true as right answer
`ButtonComponent btnCmp = new ButtonComponent(ButtonType.TRUE_FALSE, true)`

Or button array (maybe Custom Button class) with correct button in second parameter

`ButtonComponent btnCmp = new ButtonComponent(buttonArray, buttonRight)`
